### ISSUE TITLE
Spider upside down

### ISSUE THREAD

**Issue by Helloausername** [ZiLko/xdBot#188]
The spider is upside down when the gravity is normal, when the gravity is flipped, the spider look like its standing on a block, android32

Sorry, i dont have a image of the spider

**Comment by Micah1101** [comment]
SAME i have no idea how to fix tho lol

**Comment by LumerGD120** [comment]
> The spider is upside down when the gravity is normal, when the gravity is flipped, the spider look like its standing on a block, android32
> 
> Sorry, i dont have a image of the spider

I have the same issue but i only see it when i have show trajectory on, i experienced this on September 6 (GMT+8), maybe just turn off trajectory if that doesn't work maybe Zilko will fix it.

**Comment by Helloausername** [comment]
i dont have trajectory on

**Comment by ZiLko** [comment]
send video and what xdbot version

**Comment by LumerGD120** [comment]
> send video and what xdbot version

Hi sorry for late reply, it was in xdbot alpha 4 i was botting Brain power (extreme demon) and when i was at the spider part i noticed that the spider is quite wrong i have the trajectory on and i turn it off and it was fine, sorry i can't recreate a video on this issue.

**Comment by Helloausername** [comment]
Fixed it in new version.

**Comment by ZiLko** [comment]
@Helloausername what mods did you have

**Comment by ZiLko** [comment]
I didnt fix it in any version so it was another mod and you uninstalled or disabled it, i need to know which mod it was
